name: shopkeeper_dashboard
description: Flutter Shopkeeper Dashboard â€“ Real-Time Chicken Order Management System
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.1
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  flutter_local_notifications: ^17.2.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
